import { createContext, useContext, useState, ReactNode } from 'react';

type Locale = 'en' | 'fr';

interface Translations {
  [key: string]: {
    en: string;
    fr: string;
  };
}

const translations: Translations = {
  // Navigation
  dashboard: { en: 'Dashboard', fr: 'Tableau de bord' },
  markets: { en: 'Markets', fr: 'Marchés' },
  leaderboard: { en: 'Leaderboard', fr: 'Classement' },
  learn: { en: 'Learn', fr: 'Apprendre' },
  profile: { en: 'Profile', fr: 'Profil' },
  admin: { en: 'Admin', fr: 'Admin' },

  // Home page
  welcome: { en: 'Welcome to Welloh', fr: 'Bienvenue sur Welloh' },
  tradingTerminal: { en: 'The professional trading terminal for everyone.', fr: 'Le terminal de trading professionnel pour tous.' },
  openAccount: { en: 'Open Trading Account', fr: 'Ouvrir un compte de trading' },
  learnMore: { en: 'Learn More', fr: 'En savoir plus' },
  globalAccess: { en: 'Global Access', fr: 'Accès mondial' },
  globalAccessDesc: { en: 'Trade across NYSE, NASDAQ, BRVM, and JSE all from a single terminal.', fr: 'Tradez sur NYSE, NASDAQ, BRVM et JSE depuis un seul terminal.' },
  aiIntelligence: { en: 'AI Intelligence', fr: 'Intelligence IA' },
  aiIntelligenceDesc: { en: 'Utilize our advanced AI mentor to analyze stocks and compare market trends in real-time.', fr: 'Utilisez notre mentor IA avancé pour analyser les actions et comparer les tendances du marché en temps réel.' },
  zeroRisk: { en: 'Zero Risk', fr: 'Zéro risque' },
  zeroRiskDesc: { en: 'Practice strategies with simulated capital. Climb the leaderboard by maximizing your Sharpe ratio.', fr: 'Pratiquez des stratégies avec du capital simulé. Grimpez au classement en maximisant votre ratio de Sharpe.' },

  // Landing View
  platformBadge: { en: 'Trading simulation platform #1', fr: 'Plateforme de simulation boursiere #1' },
  pilotFuture: { en: 'Pilot your financial future', fr: 'Pilotez votre avenir financier' },
  simulateAnalyzeExcel: { en: 'Simulate, analyze, excel.', fr: 'Simulez, analysez, excellez.' },
  trainRiskFree: { en: 'Train risk-free on global and African markets, analyze with AI, and turn your performances into career opportunities.', fr: 'Entrainez-vous sans risque sur les marches mondiaux et africains, analysez avec l\'IA, et transformez vos performances en opportunites de carriere.' },
  startFree: { en: 'Start for free', fr: 'Commencer gratuitement' },
  activeTraders: { en: 'Active traders', fr: 'Traders actifs' },
  simulatedVolume: { en: 'Simulated volume', fr: 'Volume simule' },
  globalExchanges: { en: 'Global exchanges', fr: 'Bourses mondiales' },
  satisfactionRate: { en: 'Satisfaction rate', fr: 'Taux de satisfaction' },
  features: { en: 'FEATURES', fr: 'FONCTIONNALITES' },
  featuresTitle: { en: 'Everything you need to excel in trading', fr: 'Tout ce dont vous avez besoin pour exceller en trading' },
  realisticSimulation: { en: 'Realistic simulation', fr: 'Simulation realiste' },
  realisticSimulationDesc: { en: 'Trade with $100,000 virtual funds on realistic market data generated by AI. No risk, maximum learning.', fr: 'Tradez avec 100 000 $ virtuels sur des donnees de marche realistes generees par IA. Aucun risque, apprentissage maximal.' },
  advancedAIAnalysis: { en: 'Advanced AI analysis', fr: 'Analyse IA avancee' },
  advancedAIAnalysisDesc: { en: 'Get financial analyses, projections and personalized recommendations for each stock in seconds.', fr: 'Obtenez des analyses financieres, projections et recommandations personnalisees pour chaque action en secondes.' },
  globalMarkets: { en: 'Global markets', fr: 'Marches mondiaux' },
  globalMarketsDesc: { en: 'Access to BRVM, JSE, NYSE, NASDAQ exchanges and more. Explore African and international opportunities.', fr: 'Acces aux bourses BRVM, JSE, NYSE, NASDAQ et plus. Explorez les opportunites africaines et internationales.' },
  competitionsLeaderboards: { en: 'Competitions & Leaderboards', fr: 'Competitions & Classements' },
  competitionsLeaderboardsDesc: { en: 'Face other traders, earn badges and climb the leaderboard to get noticed.', fr: 'Affrontez d\'autres traders, gagnez des badges et grimpez dans le leaderboard pour vous faire reperer.' },
  integratedTraining: { en: 'Integrated training', fr: 'Formation integree' },
  integratedTrainingDesc: { en: 'Educational modules, interactive tutorials and AI mentor to improve your investment strategies.', fr: 'Modules educatifs, tutoriels interactifs et mentor IA pour ameliorer vos strategies d\'investissement.' },
  maximumSecurity: { en: 'Maximum security', fr: 'Securite maximale' },
  maximumSecurityDesc: { en: 'Bank-level encryption and best security practices to protect your information.', fr: 'Cryptage de niveau bancaire et meilleures pratiques de securite pour proteger vos informations.' },
  howItWorks: { en: 'HOW IT WORKS', fr: 'COMMENT CA MARCHE' },
  becomeExpert3Steps: { en: 'Become an expert in 3 simple steps', fr: 'Devenez un expert en 3 etapes simples' },
  signUp: { en: 'Sign up', fr: 'Inscrivez-vous' },
  signUpDesc: { en: 'Create your account for free and receive $100,000 virtual funds to start.', fr: 'Creez votre compte gratuitement et recevez 100 000 $ virtuels pour commencer.' },
  simulate: { en: 'Simulate', fr: 'Simulez' },
  simulateDesc: { en: 'Buy and sell stocks on global markets with realistic data.', fr: 'Achetez et vendez des actions sur les marches mondiaux avec des donnees realistes.' },
  excel: { en: 'Excel', fr: 'Excellez' },
  excelDesc: { en: 'Analyze your performances, improve yourself and get noticed by recruiters.', fr: 'Analysez vos performances, ameliorez-vous et faites-vous reperer par les recruteurs.' },
  testimonials: { en: 'TESTIMONIALS', fr: 'TEMOIGNAGES' },
  testimonialsTitle: { en: 'What our traders say', fr: 'Ce que disent nos' },
  traders: { en: 'traders', fr: 'traders' },
  testimonialsTrusted: { en: 'They trust us', fr: 'ILS NOUS FONT CONFIANCE' },
  testimonial1: { en: 'Thanks to Welloh, I was able to train and land my first job in finance. The AI analysis is incredible!', fr: 'Grace a Welloh, j\'ai pu m\'entrainer et decrocher mon premier poste dans la finance. L\'analyse IA est incroyable!' },
  testimonial2: { en: 'The best platform to learn trading. The competitions really motivated me to improve.', fr: 'La meilleure plateforme pour apprendre le trading. Les competitions m\'ont vraiment motive a m\'ameliorer.' },
  testimonial3: { en: 'I recommend Welloh to all my junior colleagues. It\'s an exceptional educational tool.', fr: 'Je recommande Welloh a tous mes collegues juniors. C\'est un outil pedagogique exceptionnel.' },
  readyJoinElite: { en: 'Ready to join the financial elite?', fr: 'Pret a rejoindre l\'elite financiere?' },
  bestTalentsNoticed: { en: 'The best talents on our platform are noticed by the largest financial institutions.', fr: 'Les meilleurs talents de notre plateforme sont reperes par les plus grandes institutions financieres.' },
  startNow: { en: 'Start now', fr: 'Commencer maintenant' },
  freeForever: { en: 'Free forever. No credit card required.', fr: 'Gratuit pour toujours. Aucune carte de credit requise.' },

  // Common
  signIn: { en: 'Sign In', fr: 'Se connecter' },
  signOut: { en: 'Sign Out', fr: 'Se déconnecter' },
  loading: { en: 'Loading...', fr: 'Chargement...' },
  error: { en: 'Error', fr: 'Erreur' },
  success: { en: 'Success', fr: 'Succès' },
};

interface I18nContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
}

const I18nContext = createContext<I18nContextType | undefined>(undefined);

export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>('en');

  const t = (key: string): string => {
    return translations[key]?.[locale] || key;
  };

  return (
    <I18nContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </I18nContext.Provider>
  );
}

export function useTranslation() {
  const context = useContext(I18nContext);
  if (!context) {
    throw new Error('useTranslation must be used within I18nProvider');
  }
  return context;
}

export function useLocale() {
  const { locale, setLocale } = useTranslation();
  return { locale, setLocale };
}